// B4AE High-Level Client API — v2.0 Protocol
//
// Mewire semua v2 protocol modules (mode negotiation, cookie challenge,
// traffic scheduler, mode binding, replay protection) ke high-level client API
// yang kompatibel dengan README quickstart.

use crate::audit::{AuditEntry, AuditEvent, AuditSink, hash_for_audit};
use crate::crypto::CryptoError;
use crate::crypto::random;
use crate::error::{B4aeError, B4aeResult};
use crate::protocol::session::Session;
use crate::protocol::message::{Message, MessageContent, EncryptedMessage};
use crate::protocol::handshake::{
    HandshakeConfig, HandshakeInitiator, HandshakeResponder,
    HandshakeInit as V1HandshakeInit,
    HandshakeResponse as V1HandshakeResponse,
    HandshakeComplete as V1HandshakeComplete,
    AlgorithmId,
};
use crate::protocol::v2::{
    AuthenticationMode, SessionId, ModeNegotiation, ModeSelection, ModeBinding,
    CookieChallenge, ClientHello,
    negotiate_authentication_mode, ModeNegotiationError,
    derive_mode_binding, verify_handshake_mode_binding, DowngradeError,
    GlobalTrafficScheduler, TrafficStatistics,
};
use crate::protocol::v2::types::{
    HandshakeInit as V2HandshakeInit,
    HandshakeResponse as V2HandshakeResponse,
    HandshakeComplete as V2HandshakeComplete,
};
use crate::protocol::v2::cookie_challenge::{generate_cookie, ServerSecret};
use crate::protocol::v2::replay_protection::ReplayProtection;
use crate::time;
use std::collections::HashMap;
use std::sync::Arc;
use bincode;

/// Pending v2 handshake state (initiator side)
struct V2InitiatorState {
    /// Authentication mode selected for this session
    mode: AuthenticationMode,
    /// Client random from ModeNegotiation (used only for mode binding)
    client_random: [u8; 32],
    /// Server random from ModeSelection (used only for mode binding)
    server_random: Option<[u8; 32]>,
    /// Mode binding (derived after mode selection)
    mode_binding: Option<ModeBinding>,
    /// Underlying v1 handshake initiator (handles all crypto heavy-lifting)
    v1_initiator: HandshakeInitiator,
    /// Cached v1 HandshakeInit — generated in initiate_handshake_v2, used to build v2 envelope
    v1_init: Option<V1HandshakeInit>,
    /// Timestamp of initiation (for timeout)
    started_at: u64,
}

/// Pending v2 handshake state (responder side)
struct V2ResponderState {
    /// Authentication mode selected for this session
    mode: AuthenticationMode,
    /// Client random received from peer (mode negotiation random, for mode binding only)
    client_random: [u8; 32],
    /// Server random generated by us (mode negotiation random, for mode binding only)
    server_random: [u8; 32],
    /// Mode binding (derived after mode selection)
    mode_binding: Option<ModeBinding>,
    /// Underlying v1 handshake responder
    v1_responder: HandshakeResponder,
    /// Cached v1 HandshakeResponse — generated in respond_to_handshake_v2
    v1_response: Option<V1HandshakeResponse>,
    /// Timestamp of initiation (for timeout)
    started_at: u64,
}

/// Server-side v2 context (cookie challenge + replay protection)
struct V2ServerContext {
    server_secret: ServerSecret,
    replay_filter: ReplayProtection,
    supported_modes: Vec<AuthenticationMode>,
}

/// B4AE v2.0 Client
///
/// Implements the full B4AE v2.0 protocol flow:
/// 1. Mode negotiation (Mode A = deniable XEdDSA, Mode B = PQ Dilithium5)
/// 2. Stateless cookie challenge (DoS protection)
/// 3. Handshake with mode-specific signatures
/// 4. Encrypted messaging via global traffic scheduler
///
/// ## Quick Start
///
/// ```rust,ignore
/// use b4ae::client_v2::B4aeClientV2;
/// use b4ae::protocol::v2::AuthenticationMode;
///
/// let mut alice = B4aeClientV2::new(AuthenticationMode::ModeA).unwrap();
/// let mut bob   = B4aeClientV2::new(AuthenticationMode::ModeB).unwrap();
///
/// let alice_id = b"alice".to_vec();
/// let bob_id   = b"bob".to_vec();
///
/// // 1. Mode negotiation
/// let negotiation = alice.initiate_mode_negotiation(&bob_id).unwrap();
/// let selection   = bob.respond_mode_negotiation(&alice_id, negotiation).unwrap();
/// alice.complete_mode_negotiation(&bob_id, selection).unwrap();
///
/// // 2. Cookie challenge (DoS protection)
/// let hello           = alice.send_client_hello(&bob_id).unwrap();
/// let cookie_response = bob.respond_cookie_challenge(&alice_id, hello).unwrap();
///
/// // 3. Handshake
/// let init     = alice.initiate_handshake_v2(&bob_id, cookie_response).unwrap();
/// let response = bob.respond_to_handshake_v2(&alice_id, init).unwrap();
/// let complete = alice.process_response_v2(&bob_id, response).unwrap();
/// bob.complete_handshake_v2(&alice_id, complete).unwrap();
/// alice.finalize_initiator_v2(&bob_id).unwrap();
///
/// // 4. Messaging
/// let encrypted = alice.encrypt_message_v2(&bob_id, b"Hello!").unwrap();
/// let plain     = bob.decrypt_message_v2(&alice_id, &encrypted).unwrap();
/// assert_eq!(plain, b"Hello!");
/// ```
pub struct B4aeClientV2 {
    /// Preferred / local authentication mode
    preferred_mode: AuthenticationMode,
    /// Supported modes advertised during negotiation
    supported_modes: Vec<AuthenticationMode>,
    /// Handshake config (reuses v1 crypto machinery)
    handshake_config: HandshakeConfig,
    /// Optional audit sink
    audit_sink: Option<Arc<dyn AuditSink>>,

    /// Active v2 sessions indexed by peer_id
    sessions: HashMap<Vec<u8>, Session>,

    /// Pending initiator handshakes
    pending_initiators: HashMap<Vec<u8>, V2InitiatorState>,
    /// Pending responder handshakes
    pending_responders: HashMap<Vec<u8>, V2ResponderState>,

    /// Server context (cookie challenge, replay protection) — populated after first
    /// `respond_cookie_challenge()` call, or can be pre-initialised via `init_server()`.
    server_ctx: Option<V2ServerContext>,

    /// Global traffic scheduler (shared across all sessions)
    traffic_scheduler: GlobalTrafficScheduler,
}

impl B4aeClientV2 {
    /// Create a new v2 client with the given preferred authentication mode.
    ///
    /// The client will advertise `preferred_mode` as its preference during
    /// mode negotiation but also support the other production-ready mode (A or B).
    pub fn new(preferred_mode: AuthenticationMode) -> B4aeResult<Self> {
        if !preferred_mode.is_production_ready() {
            return Err(B4aeError::ConfigError(format!(
                "Mode {:?} is not production-ready", preferred_mode
            )));
        }

        // Advertise both production-ready modes; prefer the caller's choice
        let supported_modes = vec![AuthenticationMode::ModeA, AuthenticationMode::ModeB];

        Ok(B4aeClientV2 {
            preferred_mode,
            supported_modes,
            handshake_config: HandshakeConfig::default(),
            audit_sink: None,
            sessions: HashMap::new(),
            pending_initiators: HashMap::new(),
            pending_responders: HashMap::new(),
            server_ctx: None,
            traffic_scheduler: GlobalTrafficScheduler::new(100.0),
        })
    }

    /// Attach an audit sink for compliance logging.
    pub fn with_audit_sink(mut self, sink: Arc<dyn AuditSink>) -> Self {
        self.audit_sink = Some(sink);
        self
    }

    /// Override the set of supported modes (must include preferred_mode).
    pub fn with_supported_modes(mut self, modes: Vec<AuthenticationMode>) -> B4aeResult<Self> {
        if !modes.contains(&self.preferred_mode) {
            return Err(B4aeError::ConfigError(
                "supported_modes must include preferred_mode".to_string()
            ));
        }
        self.supported_modes = modes;
        Ok(self)
    }

    // ─────────────────────────────────────────────────────────────────────────
    // STEP 1 — MODE NEGOTIATION
    // ─────────────────────────────────────────────────────────────────────────

    /// **[Client]** Initiate mode negotiation with a peer.
    ///
    /// Returns a `ModeNegotiation` message to send to the server.
    pub fn initiate_mode_negotiation(&mut self, peer_id: &[u8]) -> B4aeResult<ModeNegotiation> {
        let mut client_random = [0u8; 32];
        random::fill_random(&mut client_random)
            .map_err(|e| B4aeError::CryptoError(e.to_string()))?;

        let negotiation = ModeNegotiation {
            supported_modes: self.supported_modes.clone(),
            preferred_mode: self.preferred_mode,
            client_random,
        };

        // Store client_random under peer_id so we can use it after mode selection
        // We store it in a placeholder initiator state (no v1_initiator yet)
        let v1_initiator = HandshakeInitiator::new(self.handshake_config.clone())
            .map_err(|e: CryptoError| B4aeError::CryptoError(e.to_string()))?;

        self.pending_initiators.insert(peer_id.to_vec(), V2InitiatorState {
            mode: self.preferred_mode, // tentative, overwritten in complete_mode_negotiation
            client_random,
            server_random: None,
            mode_binding: None,
            v1_initiator,
            v1_init: None,
            started_at: time::current_time_secs(),
        });

        if let Some(sink) = &self.audit_sink {
            sink.log(AuditEntry::new(
                AuditEvent::HandshakeInitiated { peer_id_hash: hash_for_audit(peer_id) },
                None,
            ));
        }

        Ok(negotiation)
    }

    /// **[Server]** Respond to a mode negotiation request.
    ///
    /// Selects a compatible mode and returns a `ModeSelection` message.
    pub fn respond_mode_negotiation(
        &mut self,
        peer_id: &[u8],
        negotiation: ModeNegotiation,
    ) -> B4aeResult<ModeSelection> {
        let selected_mode = negotiate_authentication_mode(&negotiation, &self.supported_modes)
            .map_err(|e: ModeNegotiationError| B4aeError::ProtocolError(e.to_string()))?;

        let mut server_random = [0u8; 32];
        random::fill_random(&mut server_random)
            .map_err(|e| B4aeError::CryptoError(e.to_string()))?;

        let client_random = negotiation.client_random;

        // Ensure server context is initialised
        self.ensure_server_ctx();

        // Derive mode binding
        let mode_binding = derive_mode_binding(&client_random, &server_random, selected_mode);

        // Create pending responder state
        let v1_responder = HandshakeResponder::new(self.handshake_config.clone())
            .map_err(|e: CryptoError| B4aeError::CryptoError(e.to_string()))?;

        self.pending_responders.insert(peer_id.to_vec(), V2ResponderState {
            mode: selected_mode,
            client_random: negotiation.client_random,
            server_random,
            mode_binding: Some(mode_binding),
            v1_responder,
            v1_response: None,
            started_at: time::current_time_secs(),
        });

        Ok(ModeSelection { selected_mode, server_random })
    }

    /// **[Client]** Complete mode negotiation after receiving server's `ModeSelection`.
    ///
    /// Derives mode binding and stores it for subsequent handshake messages.
    pub fn complete_mode_negotiation(
        &mut self,
        peer_id: &[u8],
        selection: ModeSelection,
    ) -> B4aeResult<()> {
        let state = self.pending_initiators.get_mut(peer_id)
            .ok_or_else(|| B4aeError::ProtocolError("No pending negotiation for peer".to_string()))?;

        if !self.supported_modes.contains(&selection.selected_mode) {
            return Err(B4aeError::ProtocolError(format!(
                "Server selected unsupported mode: {:?}", selection.selected_mode
            )));
        }

        let mode_binding = derive_mode_binding(
            &state.client_random,
            &selection.server_random,
            selection.selected_mode,
        );

        state.mode = selection.selected_mode;
        state.server_random = Some(selection.server_random);
        state.mode_binding = Some(mode_binding);

        Ok(())
    }

    // ─────────────────────────────────────────────────────────────────────────
    // STEP 2 — COOKIE CHALLENGE (DoS protection)
    // ─────────────────────────────────────────────────────────────────────────

    /// **[Client]** Send a minimal ClientHello to trigger a cookie challenge.
    pub fn send_client_hello(&self, peer_id: &[u8]) -> B4aeResult<ClientHello> {
        let state = self.pending_initiators.get(peer_id)
            .ok_or_else(|| B4aeError::ProtocolError("No pending negotiation — call initiate_mode_negotiation first".to_string()))?;

        Ok(ClientHello {
            client_random: state.client_random,
            timestamp: time::current_time_secs(),
        })
    }

    /// **[Server]** Respond to a ClientHello with a stateless cookie challenge.
    ///
    /// Returns a `CookieChallenge` that the client must echo back.
    pub fn respond_cookie_challenge(
        &mut self,
        peer_id: &[u8],
        hello: ClientHello,
    ) -> B4aeResult<CookieChallenge> {
        self.ensure_server_ctx();

        let server_ctx = self.server_ctx.as_mut().unwrap();

        let mut server_random = [0u8; 32];
        random::fill_random(&mut server_random)
            .map_err(|e| B4aeError::CryptoError(e.to_string()))?;

        let cookie_bytes = generate_cookie(
            &server_ctx.server_secret,
            "peer",           // IP not available in library context; use neutral placeholder
            hello.timestamp,
            &hello.client_random,
        ).map_err(|e| B4aeError::ProtocolError(e.to_string()))?;

        let mut cookie = [0u8; 32];
        cookie.copy_from_slice(&cookie_bytes);

        // If there is already a pending responder for this peer, update client_random
        if let Some(state) = self.pending_responders.get_mut(peer_id) {
            state.client_random = hello.client_random;
        }

        Ok(CookieChallenge { cookie, server_random })
    }

    // ─────────────────────────────────────────────────────────────────────────
    // STEP 3 — HANDSHAKE
    // ─────────────────────────────────────────────────────────────────────────

    /// **[Client]** Initiate v2 handshake after cookie challenge.
    ///
    /// `cookie_challenge` is the `CookieChallenge` received from the server.
    /// Returns a `V2HandshakeInit` to send to the server.
    pub fn initiate_handshake_v2(
        &mut self,
        peer_id: &[u8],
        _cookie_challenge: CookieChallenge,
    ) -> B4aeResult<V2HandshakeInit> {
        let state = self.pending_initiators.get_mut(peer_id)
            .ok_or_else(|| B4aeError::ProtocolError("No pending v2 handshake for peer".to_string()))?;

        let mode_binding = state.mode_binding.clone()
            .ok_or_else(|| B4aeError::ProtocolError("Mode binding not set — complete mode negotiation first".to_string()))?;

        // Generate v1 HandshakeInit (contains ephemeral keys, signature, client_random)
        let v1_init = state.v1_initiator.generate_init()
            .map_err(|e: CryptoError| B4aeError::CryptoError(e.to_string()))?;

        // Serialize the full v1 init into ephemeral_kyber for transport.
        // The responder will deserialize it and feed it to their v1 HandshakeResponder.
        let v1_init_bytes = bincode::serialize(&v1_init)
            .map_err(|e| B4aeError::CryptoError(format!("Serialize v1_init: {e}")))?;

        let timestamp = time::current_time_secs();
        let ephemeral_x25519 = state.client_random; // mode-negotiation binding anchor

        // Cache for reference (not needed for crypto, kept for debugging)
        state.v1_init = Some(v1_init);

        Ok(V2HandshakeInit {
            ephemeral_x25519,
            ephemeral_kyber: v1_init_bytes,
            signature: vec![0u8; 1], // placeholder — real sig is inside ephemeral_kyber payload
            timestamp,
            mode_binding,
        })
    }

    /// **[Server]** Respond to a v2 HandshakeInit.
    ///
    /// Verifies mode binding, processes the init via v1 machinery, returns HandshakeResponse.
    pub fn respond_to_handshake_v2(
        &mut self,
        peer_id: &[u8],
        init: V2HandshakeInit,
    ) -> B4aeResult<V2HandshakeResponse> {
        let state = self.pending_responders.get_mut(peer_id)
            .ok_or_else(|| B4aeError::ProtocolError("No pending v2 responder for peer".to_string()))?;

        let mode_binding = state.mode_binding.clone()
            .ok_or_else(|| B4aeError::ProtocolError("Mode binding not set".to_string()))?;

        // Verify mode binding to prevent downgrade attacks
        verify_handshake_mode_binding(
            &init.mode_binding,
            &state.client_random,
            &state.server_random,
            state.mode,
        ).map_err(|e: DowngradeError| B4aeError::ProtocolError(e.to_string()))?;

        // Deserialize the v1 HandshakeInit that was serialized by the initiator
        let v1_init: V1HandshakeInit = bincode::deserialize(&init.ephemeral_kyber)
            .map_err(|e| B4aeError::CryptoError(format!("Deserialize v1_init: {e}")))?;

        // Feed into v1 responder — this does the real crypto (signature verify, Kyber encaps)
        let v1_response = state.v1_responder.process_init(v1_init)
            .map_err(|e: CryptoError| B4aeError::CryptoError(e.to_string()))?;

        // Serialize the full v1 response for transport back to initiator
        let v1_response_bytes = bincode::serialize(&v1_response)
            .map_err(|e| B4aeError::CryptoError(format!("Serialize v1_response: {e}")))?;

        // Cache v1_response for finalization step
        state.v1_response = Some(v1_response);

        let timestamp = time::current_time_secs();

        Ok(V2HandshakeResponse {
            ephemeral_x25519: state.server_random,
            ephemeral_kyber: v1_response_bytes,
            signature: vec![0u8; 1], // placeholder — real sig inside ephemeral_kyber payload
            timestamp,
            mode_binding,
        })
    }

    /// **[Client]** Process v2 HandshakeResponse and return HandshakeComplete.
    pub fn process_response_v2(
        &mut self,
        peer_id: &[u8],
        response: V2HandshakeResponse,
    ) -> B4aeResult<V2HandshakeComplete> {
        let state = self.pending_initiators.get_mut(peer_id)
            .ok_or_else(|| B4aeError::ProtocolError("No pending initiator for peer".to_string()))?;

        let mode_binding = state.mode_binding.clone()
            .ok_or_else(|| B4aeError::ProtocolError("Mode binding not set".to_string()))?;

        let server_random = state.server_random
            .ok_or_else(|| B4aeError::ProtocolError("No server random — complete mode negotiation first".to_string()))?;

        // Verify mode binding against mode-negotiation randoms
        verify_handshake_mode_binding(
            &response.mode_binding,
            &state.client_random,
            &server_random,
            state.mode,
        ).map_err(|e: DowngradeError| B4aeError::ProtocolError(e.to_string()))?;

        // Deserialize the v1 HandshakeResponse that was serialized by the responder
        let v1_response: V1HandshakeResponse = bincode::deserialize(&response.ephemeral_kyber)
            .map_err(|e| B4aeError::CryptoError(format!("Deserialize v1_response: {e}")))?;

        // Feed into v1 initiator — verifies signature and decapsulates Kyber shared secret
        state.v1_initiator.process_response(v1_response)
            .map_err(|e: CryptoError| B4aeError::CryptoError(e.to_string()))?;

        // Generate v1 HandshakeComplete (confirmation + signature)
        let v1_complete = state.v1_initiator.generate_complete()
            .map_err(|e: CryptoError| B4aeError::CryptoError(e.to_string()))?;

        // Serialize v1 complete for transport
        let v1_complete_bytes = bincode::serialize(&v1_complete)
            .map_err(|e| B4aeError::CryptoError(format!("Serialize v1_complete: {e}")))?;

        let timestamp = time::current_time_secs();

        Ok(V2HandshakeComplete {
            signature: v1_complete_bytes, // carries full v1 complete payload
            timestamp,
            mode_binding,
        })
    }

    /// **[Server]** Process v2 HandshakeComplete and finalize the session.
    pub fn complete_handshake_v2(
        &mut self,
        peer_id: &[u8],
        complete: V2HandshakeComplete,
    ) -> B4aeResult<()> {
        let state = self.pending_responders.remove(peer_id)
            .ok_or_else(|| B4aeError::ProtocolError("No pending responder for peer".to_string()))?;

        // Verify mode binding against mode-negotiation randoms
        verify_handshake_mode_binding(
            &complete.mode_binding,
            &state.client_random,
            &state.server_random,
            state.mode,
        ).map_err(|e: DowngradeError| B4aeError::ProtocolError(e.to_string()))?;

        // Deserialize v1 HandshakeComplete from signature field
        let v1_complete: V1HandshakeComplete = bincode::deserialize(&complete.signature)
            .map_err(|e| B4aeError::CryptoError(format!("Deserialize v1_complete: {e}")))?;

        let mut responder = state.v1_responder;
        responder.process_complete(v1_complete)
            .map_err(|e: CryptoError| B4aeError::CryptoError(e.to_string()))?;

        let result = responder.finalize()
            .map_err(|e: CryptoError| B4aeError::CryptoError(e.to_string()))?;

        let session = Session::from_handshake(result, peer_id.to_vec(), self.audit_sink.clone())
            .map_err(|e: CryptoError| B4aeError::CryptoError(e.to_string()))?;

        if let Some(sink) = &self.audit_sink {
            sink.log(AuditEntry::new(
                AuditEvent::HandshakeCompleted { peer_id_hash: hash_for_audit(peer_id) },
                None,
            ));
            sink.log(AuditEntry::new(
                AuditEvent::SessionCreated { session_id_hash: hash_for_audit(session.session_id()) },
                None,
            ));
        }

        self.sessions.insert(peer_id.to_vec(), session);
        Ok(())
    }

    /// **[Client]** Finalize initiator-side handshake and create session.
    pub fn finalize_initiator_v2(&mut self, peer_id: &[u8]) -> B4aeResult<()> {
        let state = self.pending_initiators.remove(peer_id)
            .ok_or_else(|| B4aeError::ProtocolError("No pending initiator for peer".to_string()))?;

        let result = state.v1_initiator.finalize()
            .map_err(|e: CryptoError| B4aeError::CryptoError(e.to_string()))?;

        let session = Session::from_handshake(result, peer_id.to_vec(), self.audit_sink.clone())
            .map_err(|e: CryptoError| B4aeError::CryptoError(e.to_string()))?;

        if let Some(sink) = &self.audit_sink {
            sink.log(AuditEntry::new(
                AuditEvent::HandshakeCompleted { peer_id_hash: hash_for_audit(peer_id) },
                None,
            ));
            sink.log(AuditEntry::new(
                AuditEvent::SessionCreated { session_id_hash: hash_for_audit(session.session_id()) },
                None,
            ));
        }

        self.sessions.insert(peer_id.to_vec(), session);
        Ok(())
    }

    // ─────────────────────────────────────────────────────────────────────────
    // STEP 4 — MESSAGING
    // ─────────────────────────────────────────────────────────────────────────

    /// **[Both]** Encrypt a message for a peer.
    ///
    /// Enqueues the message into the global traffic scheduler for metadata protection.
    /// Returns the `EncryptedMessage` ready to send.
    pub fn encrypt_message_v2(
        &mut self,
        peer_id: &[u8],
        plaintext: &[u8],
    ) -> B4aeResult<EncryptedMessage> {
        if plaintext.len() > crate::MAX_MESSAGE_SIZE {
            return Err(B4aeError::InvalidInput(format!(
                "Message too large: {} > {}", plaintext.len(), crate::MAX_MESSAGE_SIZE
            )));
        }

        let session = self.sessions.get_mut(peer_id)
            .ok_or_else(|| B4aeError::ProtocolError("No session with peer — complete handshake first".to_string()))?;

        let message = Message::binary(plaintext.to_vec());
        let encrypted = session.send(&message)
            .map_err(|e: CryptoError| B4aeError::CryptoError(e.to_string()))?;

        // Schedule via global traffic scheduler for metadata protection
        let sid = SessionId::new(*session.session_id());
        let _ = self.traffic_scheduler.schedule_message(sid, encrypted.payload.clone(), false);

        Ok(encrypted)
    }

    /// **[Both]** Decrypt a message from a peer.
    ///
    /// Returns the plaintext, or an empty `Vec` if it was a dummy traffic message.
    pub fn decrypt_message_v2(
        &mut self,
        peer_id: &[u8],
        encrypted: &EncryptedMessage,
    ) -> B4aeResult<Vec<u8>> {
        let session = self.sessions.get_mut(peer_id)
            .ok_or_else(|| B4aeError::ProtocolError("No session with peer".to_string()))?;

        let message = session.receive(encrypted)
            .map_err(|e: CryptoError| B4aeError::CryptoError(e.to_string()))?;

        let data = match &message.content {
            MessageContent::Dummy => return Ok(vec![]),
            MessageContent::Binary(d) => d.clone(),
            MessageContent::Text(t) => t.clone().into_bytes(),
            MessageContent::File { data, .. } => data.clone(),
        };

        Ok(data)
    }

    // ─────────────────────────────────────────────────────────────────────────
    // SESSION MANAGEMENT
    // ─────────────────────────────────────────────────────────────────────────

    /// Returns `true` if an established session exists with the given peer.
    pub fn has_session(&self, peer_id: &[u8]) -> bool {
        self.sessions.contains_key(peer_id)
    }

    /// Close and remove a session with a peer.
    pub fn close_session(&mut self, peer_id: &[u8]) {
        if let Some(mut session) = self.sessions.remove(peer_id) {
            if let Some(sink) = &self.audit_sink {
                sink.log(AuditEntry::new(
                    AuditEvent::SessionClosed {
                        session_id_hash: hash_for_audit(session.session_id()),
                    },
                    None,
                ));
            }
            session.close();
        }
    }

    /// Remove inactive sessions older than `max_inactive_secs`.
    pub fn cleanup_inactive_sessions(&mut self, max_inactive_secs: u64) {
        let now = time::current_time_secs();
        self.sessions.retain(|_, session| {
            let inactive = now.saturating_sub(session.info().last_activity);
            inactive < max_inactive_secs
        });
    }

    /// Remove stale pending handshakes (timed out after 60 s).
    pub fn cleanup_stale_handshakes(&mut self) {
        let now = time::current_time_secs();
        self.pending_initiators.retain(|_, s| now.saturating_sub(s.started_at) < 60);
        self.pending_responders.retain(|_, s| now.saturating_sub(s.started_at) < 60);
    }

    /// Combined cleanup: sessions + stale handshakes.
    pub fn cleanup_old_state(&mut self) {
        self.cleanup_inactive_sessions(3600);
        self.cleanup_stale_handshakes();
    }

    /// Return the current authentication mode of this client.
    pub fn preferred_mode(&self) -> AuthenticationMode {
        self.preferred_mode
    }

    /// Return a reference to the traffic scheduler statistics.
    pub fn traffic_scheduler_stats(&self) -> &TrafficStatistics {
        self.traffic_scheduler.statistics()
    }

    // ─────────────────────────────────────────────────────────────────────────
    // INTERNAL HELPERS
    // ─────────────────────────────────────────────────────────────────────────

    fn ensure_server_ctx(&mut self) {
        if self.server_ctx.is_none() {
            self.server_ctx = Some(V2ServerContext {
                server_secret: ServerSecret::generate(),
                replay_filter: ReplayProtection::new(),
                supported_modes: self.supported_modes.clone(),
            });
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// TESTS
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new_mode_a() {
        let client = B4aeClientV2::new(AuthenticationMode::ModeA).unwrap();
        assert_eq!(client.preferred_mode(), AuthenticationMode::ModeA);
    }

    #[test]
    fn test_new_mode_b() {
        let client = B4aeClientV2::new(AuthenticationMode::ModeB).unwrap();
        assert_eq!(client.preferred_mode(), AuthenticationMode::ModeB);
    }

    #[test]
    fn test_new_mode_c_rejected() {
        let result = B4aeClientV2::new(AuthenticationMode::ModeC);
        assert!(result.is_err());
    }

    #[test]
    fn test_mode_negotiation_roundtrip() {
        let mut alice = B4aeClientV2::new(AuthenticationMode::ModeA).unwrap();
        let mut bob   = B4aeClientV2::new(AuthenticationMode::ModeB).unwrap();

        let alice_id = b"alice".to_vec();
        let bob_id   = b"bob".to_vec();

        let negotiation = alice.initiate_mode_negotiation(&bob_id).unwrap();
        let selection   = bob.respond_mode_negotiation(&alice_id, negotiation).unwrap();

        assert!(selection.selected_mode.is_production_ready());

        alice.complete_mode_negotiation(&bob_id, selection).unwrap();
    }

    #[test]
    fn test_client_hello_requires_negotiation() {
        let alice  = B4aeClientV2::new(AuthenticationMode::ModeA).unwrap();
        let bob_id = b"bob".to_vec();

        // Should fail — no negotiation yet
        assert!(alice.send_client_hello(&bob_id).is_err());
    }

    #[test]
    fn test_full_v2_handshake_and_messaging() {
        let mut alice = B4aeClientV2::new(AuthenticationMode::ModeA).unwrap();
        let mut bob   = B4aeClientV2::new(AuthenticationMode::ModeA).unwrap();

        let alice_id = b"alice".to_vec();
        let bob_id   = b"bob".to_vec();

        // 1. Mode negotiation
        let negotiation = alice.initiate_mode_negotiation(&bob_id).unwrap();
        let selection   = bob.respond_mode_negotiation(&alice_id, negotiation).unwrap();
        alice.complete_mode_negotiation(&bob_id, selection).unwrap();

        // 2. Cookie challenge
        let hello    = alice.send_client_hello(&bob_id).unwrap();
        let challenge = bob.respond_cookie_challenge(&alice_id, hello).unwrap();

        // 3. Handshake
        let init     = alice.initiate_handshake_v2(&bob_id, challenge).unwrap();
        let response = bob.respond_to_handshake_v2(&alice_id, init).unwrap();
        let complete = alice.process_response_v2(&bob_id, response).unwrap();
        bob.complete_handshake_v2(&alice_id, complete).unwrap();
        alice.finalize_initiator_v2(&bob_id).unwrap();

        assert!(alice.has_session(&bob_id));
        assert!(bob.has_session(&alice_id));

        // 4. Messaging
        let plaintext = b"Hello, B4AE v2.0!";
        let enc  = alice.encrypt_message_v2(&bob_id, plaintext).unwrap();
        let dec  = bob.decrypt_message_v2(&alice_id, &enc).unwrap();
        assert_eq!(dec, plaintext);
    }

    #[test]
    fn test_cleanup_no_panic() {
        let mut client = B4aeClientV2::new(AuthenticationMode::ModeA).unwrap();
        client.cleanup_old_state(); // must not panic on empty state
    }
}
